version: '3'
services:
  app_ocean:
    container_name: node_ocean
    image: ocean/hackathon:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bin:/usr/local/scripts
      - ./vamos-a-la-playa:/app
      - /app/node_modules
    networks:
      - frontend
    ports:
      - 3005:5173
    command: sh -c "pnpm run devhost"
    # restart: always
    tty: true
networks:
  frontend:
      driver: bridge