# fly.toml app configuration file generated for vamos-a-la-playa on 2023-11-12T18:47:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vamos-a-la-playa"
primary_region = "scl"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 2
  processes = ["app"]
