
export interface Beach {
    id: number;
    title: string;
    region: string;
    plastic_index: number;
    danger_index: number;
    details: string;
}


export const BEACHES: Beach[] = [
    { id: 1, title: 'Niebla', region: 'Región de los Ríos', plastic_index: 13, danger_index: 35, details: 'La Playa Niebla se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 2, title: 'Trocadero', region: 'Región de Antofagasta', plastic_index: 13, danger_index: 35, details: 'La Playa Trocadero se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 3, title: 'Lenga', region: 'Región de Antofagasta', plastic_index: 13, danger_index: 35, details: 'La Playa Lenga se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 4, title: 'XXXX', region: 'Región de Antofagasta', plastic_index: 13, danger_index: 35, details: 'La Playa XXXX se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 5, title: 'YYYY', region: 'Región del Maule', plastic_index: 13, danger_index: 35, details: 'La Playa YYYY se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 6, title: 'ZZZZ', region: 'Región de los Lagos', plastic_index: 13, danger_index: 35, details: 'La Playa ZZZZ se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 7, title: 'AAAA', region: 'Región del Biobio', plastic_index: 13, danger_index: 35, details: 'La Playa AAAA se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 8, title: 'BBBB', region: 'Región de Los Lagos', plastic_index: 13, danger_index: 35, details: 'La Playa BBBB se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 9, title: 'CCCC', region: 'Región de Aysen', plastic_index: 13, danger_index: 35, details: 'La Playa CCCC se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 10, title: 'DDDD', region: 'Región de Araucanía', plastic_index: 13, danger_index: 35, details: 'La Playa DDDD se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 11, title: 'EEEE', region: 'Región de los Ríos', plastic_index: 13, danger_index: 35, details: 'La Playa EEEE se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 12, title: 'FFFF', region: 'Región Metropolitana', plastic_index: 13, danger_index: 35, details: 'La Playa FFFF se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 13, title: 'GGGG', region: 'Región X', plastic_index: 13, danger_index: 35, details: 'La Playa GGGG se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 14, title: 'HHHH', region: 'Región Y', plastic_index: 13, danger_index: 35, details: 'La Playa HHHH se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 15, title: 'IIII', region: 'Región Z', plastic_index: 13, danger_index: 35, details: 'La Playa IIII se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 16, title: 'JJJJ', region: 'Región W', plastic_index: 13, danger_index: 35, details: 'La Playa JJJJ se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 17, title: 'KKKK', region: 'Región B', plastic_index: 13, danger_index: 35, details: 'La Playa KKKK se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
    { id: 18, title: 'LLLL', region: 'Región C', plastic_index: 13, danger_index: 35, details: 'La Playa LLLL se encuentra en el norte de Chile, en la ciudad de Antofagasta, la cual tiene una población aproximada de 361,873 habitantes. La playa es conocida por su belleza natural y su ambiente relajante, siendo uno de los destinos más populares en la Región de Antofagasta para disfrutar del mar y el clima cálido.' },
];


export const BIO_FLORA = {

}